name: publish

on:
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1.5.3

      - name: ğŸ“¦ Install Dependencies
        run: flutter packages get

      - name: ğŸ§¹ Format
        run: flutter format --set-exit-if-changed .

      - name: ğŸ“Š Analyze
        run: flutter analyze lib test example

      - name: ğŸ§ª Run tests 
        run: flutter test --no-pub

      - name: ğŸ”§ Build demo tests 
        working-directory: ./example/
        run: flutter build web
      
      - name: ğŸš€ Deploy demo website 
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages 
          folder: example/build/web/